import { GoogleOAuthProvider } from "@react-oauth/google";
import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.css";
import LayoutCompo from "./LayoutCompo";

export const metadata = {
  title: "DAF",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        {/* FIX: Change crossOrigin to crossOrigin="anonymous" */}
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link 
          href="https://fonts.googleapis.com/css2?family=Bpmf+Zihi+Kai+Std&display=swap" 
          rel="stylesheet"
        />
      </head>
      
      {/* NOTE: If you still see hydration errors related to extensions 
         like "cz-shortcut-listen", you can suppress the warning by adding 
         suppressHydrationWarning to the body tag.
      */}
      <body className="b-font" suppressHydrationWarning={true}>
        <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID}>
          <LayoutCompo>
            <Header />
            {children}
            <Footer />
          </LayoutCompo>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}