
import { GoogleOAuthProvider } from "@react-oauth/google";
import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.css";
import LayoutCompo from "./LayoutCompo";

 
export const metadata = {
  title: "DAF",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

<head>

<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin  />
<link href="https://fonts.googleapis.com/css2?family=Bpmf+Zihi+Kai+Std&display=swap" rel="stylesheet"></link>

</head>
      <body className="b-font">
             <GoogleOAuthProvider  clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID}>
        <LayoutCompo>

       
       <Header />
        {children}
        <Footer />
         </LayoutCompo>
         </GoogleOAuthProvider>
      </body>
    </html>
  ); 
}
